//! Embeds the built `af` debug console (`console/dist/`, produced by
//! `npm --prefix console run build`) into the `af` binary, and serves it
//! back out through [`asset`].
//!
//! ## Mount contract
//!
//! The `af watch --debug` HTTP server owns routing. Its job is: for any
//! request whose path does **not** match `/debug/*`, call
//! [`asset`] with the request path (leading `/` and any query string are
//! fine — `asset` strips both). `Some(StaticAsset)` is a 200: write
//! `bytes` with a `Content-Type: {content_type}` header, and ideally
//! `Cache-Control: no-cache` plus `ETag: {etag}` (the console rebuilds
//! often during development; letting the browser revalidate on the ETag
//! rather than blindly cache avoids ever debugging a stale UI).
//! `None` is a 404 — there is no SPA-style fallback-to-index, because every
//! real route the console needs (`/`, `/index.html`, hashed
//! `/assets/*`) resolves directly; an unmatched path is just wrong, not a
//! client-side route to catch.
//!
//! ## Build pipeline
//!
//! `console/dist/` must exist *before* `cargo build` runs
//! `build.rs`, because `build.rs` only copies it — it never invokes `npm`.
//! The intended ordering is:
//!
//! ```text
//! npm --prefix console run build   # produces console/dist/
//! cargo build                      # embeds it into af-console
//! ```
//!
//! Skip the first step (a fresh checkout, CI cargo-only jobs, local
//! iteration on the Rust side) and `build.rs` still succeeds: it embeds a
//! minimal placeholder page instead, and prints a `cargo:warning` so the
//! gap is visible in build output rather than silently shipping stale or
//! missing UI. [`is_placeholder`] lets a caller (or a test) tell which case
//! is embedded at runtime.
//!
//! ## ETags
//!
//! `etag` is computed lazily, once per distinct asset path, the first time
//! that path is requested — not at compile time. `build.rs` doesn't hash
//! anything; `asset()` FNV-1a hashes `file.contents()` on first access and
//! caches the result (leaked to a `&'static str`, which
//! [`StaticAsset::etag`] requires) behind a [`OnceLock`]-guarded map. The
//! embedded file set is fixed at compile time and is the same handful of
//! bundle files every request draws from, so the cache is bounded, not a
//! per-request leak.

use std::collections::HashMap;
use std::path::Path;
use std::sync::{Mutex, OnceLock};

use include_dir::{include_dir, Dir};

static ASSETS: Dir<'_> = include_dir!("$OUT_DIR/dist");

// Generated by build.rs: `const IS_PLACEHOLDER: bool = ...;`
include!(concat!(env!("OUT_DIR"), "/placeholder_flag.rs"));

/// One embedded file, ready to write straight into an HTTP response.
pub struct StaticAsset {
    pub bytes: &'static [u8],
    pub content_type: &'static str,
    pub etag: &'static str,
}

/// Resolves a request path against the embedded console bundle.
///
/// `""`, `"/"` and `"/index.html"` all resolve to the bundle's
/// `index.html`. Any other path is looked up relative to the bundle root
/// after stripping a single leading `/` and dropping a `?query`. A path
/// containing a `..` segment (anywhere, not just at the start — e.g.
/// `/assets/../../etc/passwd`) returns `None` rather than being resolved,
/// same as any path that simply isn't in the bundle: `asset` never reaches
/// outside `console/dist/`.
pub fn asset(path: &str) -> Option<StaticAsset> {
    let key = normalize(path)?;
    let key = if key.is_empty() { "index.html" } else { &key };

    let file = ASSETS.get_file(key)?;
    let content_type = content_type_for(file.path());
    let etag = etag_for(key, file.contents());

    Some(StaticAsset {
        bytes: file.contents(),
        content_type,
        etag,
    })
}

/// `true` when the embedded bundle is `build.rs`'s placeholder page rather
/// than a real `console/dist` build.
pub fn is_placeholder() -> bool {
    IS_PLACEHOLDER
}

/// Strips a leading `/` and a trailing `?query`, collapses repeated and
/// empty path segments (so `//assets//x.js` and `/assets/x.js` both resolve
/// to `assets/x.js`), and rejects any path with a `..` segment. Returns the
/// empty string for `""`, `"/"` and `"//"` alike, which callers map to
/// `index.html`.
fn normalize(path: &str) -> Option<String> {
    let without_query = path.split('?').next().unwrap_or("");

    let mut segments: Vec<&str> = Vec::new();
    for segment in without_query.split('/') {
        if segment.is_empty() {
            continue;
        }
        if segment == ".." {
            return None;
        }
        segments.push(segment);
    }

    Some(segments.join("/"))
}

/// Content type from a file extension, defaulting to
/// `application/octet-stream` for anything not in the table below — every
/// extension a Vite build actually emits should be listed here.
fn content_type_for(path: &Path) -> &'static str {
    match path.extension().and_then(|ext| ext.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("woff2") => "font/woff2",
        Some("svg") => "image/svg+xml",
        Some("json") => "application/json",
        Some("map") => "application/json",
        Some("txt") => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

/// Per-path ETag cache, populated lazily on first access to a given path.
/// Entries are never evicted: the key space is the fixed set of paths in
/// the embedded bundle, not anything request-controlled.
static ETAG_CACHE: OnceLock<Mutex<HashMap<String, &'static str>>> = OnceLock::new();

/// Returns (computing and caching on first call) the ETag for the asset at
/// `key`, hashing `bytes` with FNV-1a.
fn etag_for(key: &str, bytes: &[u8]) -> &'static str {
    let cache = ETAG_CACHE.get_or_init(|| Mutex::new(HashMap::new()));

    // A poisoned lock still holds a perfectly usable map — a panic while
    // *holding* this lock never happens (no panicking calls between lock
    // and unlock below) — so recovering it is safe rather than a mask of
    // corrupted state.
    let mut cache = cache
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());

    if let Some(etag) = cache.get(key) {
        return etag;
    }

    let etag: &'static str = Box::leak(format!("\"{}\"", fnv1a_hex(bytes)).into_boxed_str());
    cache.insert(key.to_string(), etag);
    etag
}

/// FNV-1a over `bytes`, formatted as 16 lowercase hex digits. Not
/// cryptographic — an ETag only needs to change when the content does,
/// which FNV-1a does reliably enough for a build's worth of static assets.
fn fnv1a_hex(bytes: &[u8]) -> String {
    const OFFSET_BASIS: u64 = 0xcbf29ce484222325;
    const PRIME: u64 = 0x0000_0100_0000_01b3;

    let mut hash = OFFSET_BASIS;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(PRIME);
    }
    format!("{hash:016x}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn index_resolves_from_empty_root_and_explicit_paths() {
        let via_empty = asset("").expect("\"\" resolves");
        let via_root = asset("/").expect("\"/\" resolves");
        let via_explicit = asset("/index.html").expect("\"/index.html\" resolves");

        assert_eq!(via_empty.bytes, via_root.bytes);
        assert_eq!(via_root.bytes, via_explicit.bytes);
        assert_eq!(via_empty.content_type, "text/html; charset=utf-8");
    }

    #[test]
    fn unknown_path_is_none() {
        assert!(asset("/does/not/exist.js").is_none());
    }

    #[test]
    fn traversal_segments_are_rejected() {
        assert!(asset("/../Cargo.toml").is_none());
        assert!(asset("/assets/../../Cargo.toml").is_none());
        assert!(asset("..").is_none());
    }

    #[test]
    fn query_strings_are_stripped_before_lookup() {
        let plain = asset("/index.html").expect("index resolves");
        let with_query = asset("/index.html?foo=bar").expect("query string is stripped");
        assert_eq!(plain.bytes, with_query.bytes);
    }

    #[test]
    fn normalize_collapses_repeated_and_empty_segments() {
        assert_eq!(normalize(""), Some(String::new()));
        assert_eq!(normalize("/"), Some(String::new()));
        assert_eq!(normalize("//"), Some(String::new()));
        assert_eq!(normalize("///"), Some(String::new()));
        assert_eq!(
            normalize("//assets//x.js"),
            normalize("/assets/x.js"),
            "a doubled slash anywhere must normalize identically to a single one"
        );
        assert_eq!(normalize("///a///b//"), Some("a/b".to_string()));
        assert_eq!(normalize("/a//b?q=1"), Some("a/b".to_string()));
    }

    #[test]
    fn normalize_still_rejects_traversal_across_doubled_slashes() {
        assert_eq!(normalize("//assets//../..//Cargo.toml"), None);
    }

    #[test]
    fn double_slashes_resolve_the_same_asset_as_single_slashes() {
        let plain_root = asset("/").expect("root resolves");
        let doubled_root = asset("//").expect("doubled root resolves the same index");
        assert_eq!(plain_root.bytes, doubled_root.bytes);

        // A real nested asset (a real console build always has one under
        // `assets/`; the placeholder bundle does not) resolves identically
        // whether or not its path is riddled with repeated slashes.
        let mut files = Vec::new();
        walk_files(&ASSETS, &mut files);
        if let Some(file) = files
            .iter()
            .find(|file| file.path().components().count() > 1)
        {
            let path = file.path().to_str().expect("utf8 path");
            let plain = asset(&format!("/{path}")).expect("plain nested path resolves");
            let doubled = asset(&format!("//{}", path.replace('/', "//")))
                .expect("doubled-slash nested path still resolves");
            assert_eq!(plain.bytes, doubled.bytes);
        }
    }

    #[test]
    fn index_html_etag_is_stable_across_repeated_lookups() {
        // Whatever's embedded (real bundle or placeholder), index.html is
        // always present with a non-empty, stable, quoted ETag.
        let first = asset("/index.html").expect("index resolves");
        let second = asset("/index.html").expect("index resolves on second call");

        assert!(!first.bytes.is_empty());
        assert!(first.etag.starts_with('"') && first.etag.ends_with('"'));
        assert_eq!(
            first.etag, second.etag,
            "etag must be stable across repeated lookups of the same asset"
        );
    }

    /// Recursively collects every file in the embedded bundle.
    /// `include_dir::Dir::files()` only lists a directory's immediate
    /// children, and a real console build's hashed JS/CSS/font assets all
    /// live under `assets/`, not at the bundle root — so a test that wants
    /// to see the whole bundle (not just `index.html`) has to walk
    /// `Dir::dirs()` itself.
    fn walk_files<'a>(dir: &'a Dir<'a>, out: &mut Vec<&'a include_dir::File<'a>>) {
        for entry in dir.entries() {
            match entry {
                include_dir::DirEntry::File(file) => out.push(file),
                include_dir::DirEntry::Dir(nested) => walk_files(nested, out),
            }
        }
    }

    #[test]
    fn different_assets_get_different_etags() {
        let mut files = Vec::new();
        walk_files(&ASSETS, &mut files);
        assert!(
            !files.is_empty(),
            "embedded bundle must contain at least one file"
        );

        if !is_placeholder() {
            // The placeholder bundle is a single index.html and trivially
            // can't demonstrate uniqueness across files; a real build
            // always has index.html plus at least one hashed assets/* file.
            assert!(
                files.len() > 1,
                "a real console build must embed more than just index.html"
            );
        }

        let etags: std::collections::HashSet<_> = files
            .iter()
            .map(|file| {
                let path = file.path().to_str().expect("utf8 path");
                asset(&format!("/{path}"))
                    .unwrap_or_else(|| {
                        panic!("recursively discovered file {path} must resolve via asset()")
                    })
                    .etag
            })
            .collect();

        assert_eq!(
            etags.len(),
            files.len(),
            "every distinct embedded file must get a distinct etag"
        );
    }

    #[test]
    fn nested_hashed_asset_resolves_by_real_path() {
        // The one real-world shape the console needs to load: a
        // multi-segment path like /assets/index-<hash>.js, discovered from
        // the actual embedded tree rather than a hardcoded hash (which
        // changes on every build).
        let mut files = Vec::new();
        walk_files(&ASSETS, &mut files);
        let nested = files
            .iter()
            .find(|file| file.path().components().count() > 1);

        match nested {
            Some(file) => {
                let path = file.path().to_str().expect("utf8 path");
                let request_path = format!("/{path}");

                let first = asset(&request_path).expect("nested asset resolves");
                let second = asset(&request_path).expect("nested asset resolves again");

                assert_eq!(first.bytes, file.contents());
                assert_eq!(first.content_type, content_type_for(file.path()));
                assert_eq!(
                    first.etag, second.etag,
                    "etag must be stable across repeated lookups of a nested asset"
                );
            }
            None => {
                // Only the single-file placeholder bundle has no nested
                // paths — a real console build always does (assets/*.js
                // and assets/*.css at minimum).
                assert!(
                    is_placeholder(),
                    "a real console build must contain a nested asset (e.g. assets/index-<hash>.js)"
                );
            }
        }
    }

    #[test]
    fn placeholder_detection_is_internally_consistent() {
        // This test runs against whichever bundle build.rs actually
        // embedded for this build (real console/dist, or the placeholder
        // written when it was absent) — so it asserts consistency with
        // is_placeholder() rather than asserting a specific mode.
        let index = asset("/index.html").expect("index.html always present");
        let looks_like_placeholder =
            std::str::from_utf8(index.bytes).is_ok_and(|html| html.contains("console not built"));

        assert_eq!(is_placeholder(), looks_like_placeholder);
    }

    #[test]
    fn content_type_table_covers_known_extensions() {
        assert_eq!(
            content_type_for(Path::new("x.html")),
            "text/html; charset=utf-8"
        );
        assert_eq!(
            content_type_for(Path::new("x.js")),
            "text/javascript; charset=utf-8"
        );
        assert_eq!(
            content_type_for(Path::new("x.css")),
            "text/css; charset=utf-8"
        );
        assert_eq!(content_type_for(Path::new("x.woff2")), "font/woff2");
        assert_eq!(content_type_for(Path::new("x.svg")), "image/svg+xml");
        assert_eq!(content_type_for(Path::new("x.json")), "application/json");
        assert_eq!(content_type_for(Path::new("x.map")), "application/json");
        assert_eq!(
            content_type_for(Path::new("x.txt")),
            "text/plain; charset=utf-8"
        );
        assert_eq!(
            content_type_for(Path::new("x.unknown_ext")),
            "application/octet-stream"
        );
        assert_eq!(
            content_type_for(Path::new("no_extension")),
            "application/octet-stream"
        );
    }
}
